# Generated by Django 2.2 on 2021-07-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.URLField(max_length=20000, unique=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.URLField()),
                ('votes', models.IntegerField(default=0)),
                ('types', models.URLField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageDuplicates.Question')),
            ],
        ),
    ]
